version: '3.7'
services:
    app: 
      build: ./animal-api-app
      ports:
        - target: 5000
          published: 5000
          protocol: tcp
    app2:
      build: ./animal-api-app2
      ports:
        - target: 5001
          published: 5001
          protocol: tcp
