version: '3.7'
services:
    app: 
      build: ./animal-api-app
      ports:
        - target: 5000
          published: 5000
          protocol: tcp
      environment: ${DATABASE_URI} 
    app2:
      build: ./animal-api-app2
      ports:
        - target: 5001
          published: 5001
          protocol: tcp
    database:
      image: mysql:5.7
      environment:
              MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
              MYSQL_DATABASE: animal
      volumes:
        - type: volume
          source: database-volume
          target: /var/lib/mysql
      ports:
        - target: 3306
          published: 3306
volume: 
  database-volume:
